# Generated by Django 5.2.16 on 2026-07-17 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="case",
            name="department",
        ),
        migrations.AddField(
            model_name="case",
            name="closed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="case",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="case",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
