# Generated by Django 5.2.16 on 2026-07-23 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0005_activitylog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activitylog",
            name="action",
            field=models.CharField(
                choices=[
                    ("CASE_CREATED", "Case Created"),
                    ("STATUS_CHANGED", "Status Changed"),
                    ("COMMENT_ADDED", "Comment Added"),
                    ("ATTACHMENT_UPLOADED", "Attachment Uploaded"),
                ],
                max_length=50,
            ),
        ),
    ]
